### PR TITLE
Assert joining gateway

### PR DESCRIPTION
**Pull request by ingorichtsmeier**
Hi @ThorbenLindhauer,

I found some leftovers in the docs: isWaitingForJoin is still mentioned.

Sorry, I forgot to remove them.

But now they are.

### CODE REVIEW

**Comment by koevskinikola** [comment]
Hi @ingorichtsmeier,

Sorry for the delay, I will review and merge the PR asap.

Best,
Nikola

**Comment by koevskinikola** [comment]
@ingorichtsmeier would you be able to rebase the branch on the current master. There are a lot of merge conflicts, and I don't want to miss anything by accident.

Best,
Nikola

**Comment by ThorbenLindhauer** [comment]
@koevskinikola I think it is only commit 2f194d8cc853d084ad154fd2212bfb3d747b25c2 that needs to be merged.

**Comment by koevskinikola** [comment]
Rebased and merged the missing commit with cf64b09.

**Pull request closed without merging**
