### PR TITLE
67 human task assert

### PR DESCRIPTION
**Pull request by margue**
Added test cases and documentation for HumanTaskAsserts.
Also, variables(), hasVariables(), hasNoVariables() assertions are added for HumanTaskAssert - making them available for other types of case assertions should be done in a new issue (including tests and documentation).

### CODE REVIEW

**Comment by martinschimak** [comment]
Hi @margue @malteser I just wanted to look into this - but according to github there seem to be conflicts. Can you please make sure that the pull request is mergeable and builds on travis ci (if yes, this shows up here at github, too, after some minutes - but this one shows the red cross above with a failure at travis ci). 

Furthermore, a small friendly reminder - for the next pull request :-) - I remember that we agreed together to open separate issues for features - so that everybody has a chance to comment on any pros and cons as early as possible. We concluded together that it is ok to mix testing commits and feature commits in a single cmmn branch pull request, but that we would like to relate the feature commits to separate feature issues and not to the generic "Test and document ..." issue. Many thanks!

**Comment by margue** [comment]
Hi @martinschimak,
mea culpa for mixing up this variable stuff with this generic issue. Next time, I will create dedicated issues.

Now, everything in this pull request seems to be fixed to me, there should be no more conflicts. Appreciating your feedback!
Thanks and regards!

**Comment by margue** [comment]
Hi @martinschimak,
did you have some time to have a look into this?
Thanks!

**Comment by martinschimak** [comment]
Will do.

**Pull request merged**
