### PR TITLE
Adapt CMMN assertion tests to CMMN 1.1 behaviour (fixes #95)

### LINKED ISSUE #95: cmmn_assertions branch broken since camunda 7.6
Even though travis says everything's ok, the branch does not work with camunda versions >= 7.6.0.

**Steps to Reproduce:**

1. checkout branch
2. fix camunda-bpm-assert/pom.xml - dependencyManagement to use ${camunda-bpm.version} instead of RELEASE (see attached [patch.txt](https://github.com/camunda/camunda-bpm-assert/files/899862/patch.txt))
2. run ` mvn clean install -Dcamunda-bpm.version=7.6.0`

To make sure that 7.5.0 is fine run:
` mvn clean install -Dcamunda-bpm.version=7.5.0`

**Travis CI**

When looking at the travis logs for builds against RELEASE, e.g. https://travis-ci.org/camunda/camunda-bpm-assert/jobs/129415357
then it can be seen that 7.5.0 is used instead of the latest release:
`Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/camunda/bpm/dmn/camunda-engine-dmn-bom/7.5.0-SNAPSHOT/maven-metadata.xml`

The cause seems to be that maven is not able to download Information about the available releases as this line indicates:
`[WARNING] Could not transfer metadata org.camunda.bpm:camunda-bom/maven-metadata.xml from/to codehaus-snapshots (https://nexus.codehaus.org/snapshots/): nexus.codehaus.org: unknown error`

### PR DESCRIPTION
**Pull request by stefanzilske**
Hi,

I have fixed the cmmn_assertions branch by adapting CMMN definitions and test cases to CMMN 1.1 behaviour (manual activation rule).

Cheers,
Stefan

### CODE REVIEW

**Comment by stefanzilske** [comment]
Btw: Due to the non backwards-compatible change with CMMN 1.1 cmmn_assertions is not incompatible with Camunda Versions _older_ than 7.6.0. anymore...

**Comment by martinschimak** [comment]
I merged this so that we can get to an alpha2 release soon. However, can you clarify a bit for me, pls. We don't have code changes, but just cmmn test case changes, right? So that would suggest to me that even though the test cases will just run with 7.6.0 the code should work with 7.5.0 and downwards, too, provided the test cases are crafted for those versions... or am I missing something?

**Comment by malteser** [comment]
Camunda changed in 7.6 the behavior of the Manual Activation Rule, that's why most models do not fit their respective tests anymore.

The assertions are still working as expected.

Please note: When testing the extension on travis against all supported Camunda versions, then the fixed tests will break on versions <7.6.

**Comment by martinschimak** [comment]
Hi @malteser Yeah, I actually know the Manual Activation Rule Problem... just wanted to be sure that I understand everything here. Thx for clarification!

**Pull request merged**
