### PR TITLE
[CAM-11087]: find elements by name

### PR DESCRIPTION
**Pull request by ingorichtsmeier**
[CAM-11087](https://app.camunda.com/jira/browse/CAM-11087)

instead of `assertThat(processInstance).isWaitingAt("Task_0834dhg")`
write `assertThat(processInstance).isWaitingAt(find("my fancy task name"))`

### CODE REVIEW

**Comment by tmetzke** [comment]
Hi Ingo,

thanks for the proposal, that looks interesting!
We'll have a more detailed view at it within the next days.
I'll keep you posted on our progress.

Best,
Tobias

**Comment by ingorichtsmeier** [comment]
I've added more tests and cleaned up the code. 

Regarding performance: You may assume it to be slow, when you parse the XML for each call of find.

So I've created large process diagrams and run performance measurements on it. 

Running a test that finds 100 tasks in a process model with 250 tasks just took 2 seconds on my developer machine. A test finding a single task in a model with 500 tasks took 0.4 seconds.

The result from surefire was:
```xml
  <testcase classname="com.camunda.consulting.ProcessUnitTest" name="testFind0001InNormal" time="0.975"/>
  <testcase classname="com.camunda.consulting.ProcessUnitTest" name="testFind100In0010TasksProcess" time="0.573"/>
  <testcase classname="com.camunda.consulting.ProcessUnitTest" name="testFind100In0050TasksProcess" time="0.525"/>
  <testcase classname="com.camunda.consulting.ProcessUnitTest" name="testFind100In0100TasksProcess" time="0.778"/>
  <testcase classname="com.camunda.consulting.ProcessUnitTest" name="testFind100In0250TasksProcess" time="2.238"/>
  <testcase classname="com.camunda.consulting.ProcessUnitTest" name="testFind100In0500TasksProcess" time="7.231"/>
  <testcase classname="com.camunda.consulting.ProcessUnitTest" name="testFindSingleIn0100TasksProcess" time="0.105"/>
  <testcase classname="com.camunda.consulting.ProcessUnitTest" name="testFindSingleIn0500TasksProcess" time="0.372"/>
  <testcase classname="com.camunda.consulting.ProcessUnitTest" name="testFindSingleIn1000TasksProcess" time="0.802"/>
```

The repository to repeat or extend the test is here: https://github.com/ingorichtsmeier/process-creation

**Comment by tmetzke** [comment]
Hi Ingo,

some thoughts on this:
1. Do you think it makes sense to include some kind of 'context' (e.g. the `processInstance` or its `processDefinition`) in the `find` method in order to limit the search? I would assume we are using the `find` in the context of another assertion, e.g. a `ProcessInstanceAssert` here, anyways. 
Otherwise, the search across all definitions seems too broad to me and might spawn false-negatives, e.g. when I have a task with the same name in another model but I am looking for the task in the model of the instance I am currently asserting and do not care about other models (which I think is totally fine in testing). Users are otherwise forced to use unique names across all models in order to use this. That doesn't seem reasonable to me. If there are multiple tasks with the same name in one model, it is of course totally valid to throw the error. 
**Side note**: It might also make sense to provide multiple `find` methods for different 'contexts' (e.g. process instance, process definition, job) or one that handles the context object transparently.
1. It might be beneficial to use the `DeploymentCache` here. You can fetch it from the `ProcessEngineConfigurationImpl`. With that, you can directly fetch the `BpmnModelInstance` for a process definition id from the cache, if it is there. If not, it will be parsed all the same but then cached for the next request. There are other helpful methods in the cache as well, maybe they spark some new ideas for you. This might save us some precious time and resources. So doing something like this should fetch a model instance:
   ```java
   ((ProcessEngineConfigurationImpl) processEngine().getProcessEngineConfiguration())
       .getDeploymentCache()
       .findBpmnModelInstanceForProcessDefinition(processDefinitionId)
   ```
1. Do we really need to build up a map of names to ids with every call? Maybe we can rather iterate through the collections of activities, events, gateways and so on and see if we can find a match. If we do, we store that id. If we find another match (in the same or one of the next collections), we note that in a Boolean. We can skip the remaining elements and collections then since we might only find more duplicates but it wouldn't add any further value. We can assert that we found an id but no duplicate afterwards with the stored id and the Boolean. This would again save resources as far as I can tell.
1. I would suggest we rather name this method `findId` in order to clarify the specific use it has.

Let me know what you think of those ideas and if I misunderstood anything here.
And thanks again for suggesting this feature since I think this is a very helpful addition!

Best,
Tobias

**Comment by ingorichtsmeier** [comment]
Hi @tmetzke ,

Thank you for the comments. 

My goal was to make the `find` as easy to use for the developer as possible. Short Name, single parameter. If the process model requires more details like a process name or process definition Id, we can offer this on top. 

The common `find()` should serve 95% of the requirements I've seen in reviews and trainings. And it will help with the Business-IT alignment with cawemo - modeler - engine as we don't need to rename the IDs anymore.

The internal implementation was test driven, the result is this simple implementation. To verify, I used the performance test and in my opinion it's good enough. Perhaps caching the map makes it more effcient, but where should it be stored?

It's worth to use the deployment cache instead of the process definition query. I will have a look into this and come back with new results.

**Comment by tmetzke** [comment]
Hi Ingo,

thanks for the quick reply.

Your reasoning sounds fine to me, so let's try to make the common `find()` as useful as possible and offer the other versions with more context on top if there are requests for them.

Concerning the internal implementation though, I think we should make this as solid as possible.  I thought about caching the map as well but I can't see where to reliably do this. So building the map internally every time simply strikes me as a waste of resources that we can use a better approach for that is not substantially more complex than the current one.

Looking forward to the next version. 
Let me know if I can help you out with anything here.

Best,
Tobias

**Comment by tmetzke** [comment]
Hi Ingo,

I looked a bit more into the code behind the `repositoryService().getBpmnModelInstance(processDefinition.getId())`, turns out it already uses the `DeploymentCache` transparently. So, no room for improvements there.

Also, I played around with my proposal for looking up the id a bit more and I think we can also leave the method as-is regarding that concern.

So overall, the code looks very nice!

Some minor things I discovered while validating my proposal:
* I would still argue that naming the method `findId` will help people to realize faster what the method does. The name `find` is simply to broad in my view, I also validated that with other members from the team.
* A little `null` check for `name` should be added in the very beginning of the method and a test for it too. Just to make it a bit more robust.
* Since the content of `DUPLICATED_NAME` is not used for the error message but rather as a marker value, we can abbreviate that value. Something like `private static final String DUPLICATED_NAME = "$DUPLICATE_NAME$"` perhaps?

Best,
Tobias

**Pull request merged**
