### PR TITLE
Feature/102 external task helper

### LINKED ISSUE #102: Provide helper methods to handle external tasks
Would be great to have basic helper methods for external task handling like
- fetchAndLock
- complete

### PR DESCRIPTION
**Pull request by margue**
Pull request for basic external task handling. Provides two helper methods

1. fetchAndLock
2. completeExternalTask

Closes #102

### CODE REVIEW

**Comment by componentDidMount** [comment]
hi @margue those copy-pasting your code snippets of this PR really helped me testing an external service task, too sad its not yet merged, it works really great. Thank you. 👍

**Comment by solo-yolo** [comment]
Hi @margue!
Do you have any plans to continue your work on this PR?

**Comment by margue** [comment]
Hi @solo-yolo, work is done. Just waiting for @martinschimak to review, merge and release it.

**Comment by zambrovski** [comment]
Hi @margue.

Feel free to create a PR against https://github.com/holunda-io/camunda-bpm-assert so we can just release it.

**Comment by tmetzke** [comment]
Hi all,

thanks to @margue for this contribution, first of all.
We have included this feature in the 3.0.0-alpha1 release based on the code provided here.

Please feel free to try it out and comment on it.

Closing this as merged.

Best,
Tobias

**Pull request closed without merging**
