### PR TITLE
59 guidelines for contributing

### PR DESCRIPTION
**Pull request by malteser**
Worked on contribution guide. Wrote down everything I could recreate from mail exchanges.

### CODE REVIEW

**Comment by martinschimak** [comment]
Many thx - can you just make sure that all the internal links to referenced Github files and issue tracker etc work - I counted at least five of them which don't work at the moment, simple relative references like e.g. `./camunda-bpm-assert/README.md` should do the job!

**Comment by malteser** [comment]
You are right, I missed the subdirectory for CMMN and README.md. 
The two links to the issue tracker are broken, too. I retained them from the original document in the assumption they work :)

You said 5 - what else is broken?

**Comment by martinschimak** [comment]
Sure, the issue tracker links were broken already! Mmh... number five is ... the "What means done" link. It has a minus sign too much.

**Comment by malteser** [comment]
Interesting. My IntelliJ plugin generates different HTML than GitHub. It appends a minus in replacement for the questionmark it seems. Thanks for pointing out, wouldn't have noticed otherwise!

    <h2><a href="#what-means-done-" name="what-means-done-" id="what-means-done-" class="anchor"></a>What means DONE?</h2>

vs.

    <h2><a id="user-content-what-means-done" class="anchor" href="#what-means-done" aria-hidden="true"><span class="octicon octicon-link"></span></a>What means DONE?</h2>

**Comment by malteser** [comment]
pushed a new commit with fixes

**Pull request merged**
