### PR TITLE
Compile Camunda BPM Assert for Java 7&8 and enable AssertJ 2&3 respectively

### PR DESCRIPTION
**Pull request by martinschimak**
Affects #90

### CODE REVIEW

**Comment by jangalinski** [comment]
mvn install does not work, the new artifacts -jdk7 and -jdk8 are installed to camunda-bpm-assert/${}/camunda-bpm-assert-${}

could you make this a real branch so I can fork and adapt?

**Comment by jangalinski** [comment]
Maybe it would be a good idea to use the assertj version as an inicator, not the java version. 
Reason:  spring-boot 1.5.x is still relying on java7 and the spring test-starter brings a dependency to assertj-2.6.
Although you are free to build a spring boot 1.5 project with java8, the transitive dependency to c-b-a-java8/assertj-3.9 is not considered. 

So in the camunda-spring-boot-starter-test I now use the c-b-a-java7 lib which might lead to confusion. 
This confusion would be resolved if the artifacts where named camunda-bpm-assert, camunda-bpm-assert2 and camunda-bpm-assert3.

**Comment by martinschimak** [comment]
Hi Jan, thank you fow looking into this! Do I understand correctly that when building a a spring boot 1.5 project with camunda-bpm-starter dependency and Java8, one could still explicitely include the dependency to camunda-bpm-assert-java8 and everything would work correctly?

**Comment by jangalinski** [comment]
well, camunda-spring-boot still builds when I remove the custom recompilation of camunda-bpm-assert and use the -java7 version. But I still have to check if it is really usable.

**Comment by falko** [comment]
Any news on this?

**Comment by martinschimak** [comment]
See https://github.com/camunda/camunda-bpm-assert/issues/90#issuecomment-416893593

**Comment by iLavryk** [comment]
Sorry for impatient
Any plans to merge it nearest time?

**Comment by martinschimak** [comment]
See new https://github.com/camunda/camunda-bpm-assert/issues/90#issuecomment-423903357

**Comment by zambrovski** [comment]
Solved here: https://github.com/holunda-io/camunda-bpm-assert

**Comment by tmetzke** [comment]
Hi all,

thanks to @martinschimak and @jangalinski for working on this!

We have included this in the 3.0.0-alpha1 release.
Instead of Java-version-based modules we introduced AssertJ-version-based modules.
You can read up on this in the [blog post](https://blog.camunda.com/post/2019/03/camunda-bpm-assert-300-alpha1-released/) as well.

Thanks again for your work on this!
Feel free to test this and comment on it.

Closing this as fixed.

Best,
Tobias

**Pull request closed without merging**
