### PR TITLE
Cmmn assertions

### PR DESCRIPTION
**Pull request by malteser**
Added basic functionality for testing CMMN models.
See [README.md](/holisticon/camunda-bpm-assert/blob/cmmn_assertions/camunda-bpm-assert/README.md#cmmn-assertions) and [Testmatrix](/holisticon/camunda-bpm-assert/blob/cmmn_assertions/camunda-bpm-assert/cmmn-testmatrix.md) for more details.

### CODE REVIEW

**Comment by martinschimak** [comment]
Hi all - as already discussed via eMail and BPMCon - many many thanks for this pull request. My feedback might take a bit of time, as this is not the usual small one and the daily work needs to be done, too. But I will do my best, asap.

**Comment by martinschimak** [comment]
Hi all. :smile: 

I am sorry that it took longer than it normally should (=message to self) to come back to you in this arena. But part of the reason was that the addition of CMMN assertions brought up the fundamental issue of how to deal with dependencies to different Camunda BPM versions without making management and release of Camunda BPM Assert more complicated than Camunda BPM Platform itself. I consider this solved now and just pushed the few necessary changes to master.

When it comes to this pull request I am in the process of reviewing (and learning myself). I want to share a few thoughts and ask you to comment in order to better understand your **motiviations** for certain approaches.

A small but important remark up front and I hope you won't take it personal: the pull request "physically" consists of quite a lot of formatting changes. Please avoid that in the future. I am open to change the formatting at a certain point in the future - when it's easy and then within one commit. But please don't do it in pull requests and especially not in feature branches which take considerably more time until they are eventually merged back into the master. When it comes to **this** pull request, I already sorted this out by cherry picking and rebasing your commits in a local branch of mine, so it is not necessary to do anything about it - consider it done! :gift: 

Many, many thanks :+1: for all the thought work which obviously already went into this CMMN assertions feature branch. I especially value that we already have a bunch of **test cases**, which are at this point - considering the tooling situation - still a bit nasty and time-consuming to generate.

A bit of **history**: when Camunda BPM Assert was in it's early draft stages, it contained quite a lot of code which wanted to make dealing with Camunda's (pragmatic, but sometimes cumbersome) 7.0 API more "fluent". Back then we called that the "Fluent Process Engine API" and argued that writing three lines of code for doing one small thing always was acceptable when doing it ten times for production code. But it's a real pain, when doing it a hundred times or more often for test code! However, long discussions with Daniel, Bernd, Simon and Jan brought us to the conclusion that it is **not** a good idea to build a more fluent process engine API (basically by providing more fluent wrappers) within a test library. The result of that discussion was that Camunda BPM Assert **does not** introduce its own (wrapper) types or other API improvements. Instead it is a very simple simple collection of static functions: static `assertThat` entry points for assertions plus a few static helper functions to quickly retrieve Camunda BPM api/interface types like `ProcessInstance` and `Task` etc, but not any other - test library specific - types.

I summed up that history, because not all of us participated in that phase. I still believe it was a very good choice for this library to go in this direction not to introduce any own API abstraction types. Camunda's API evolved quite a bit since then and many things became easier and more "fluent" to use. It would have been a real mess to have those Camunda driven API improvements mixed with API-like abstractions just known to and just usable within Camunda BPM Assert. I expect such improvements of the API to happen in the CMMN arena, too.

Having said that, I believe to understand of course your motivation why you exposed certain `Holder` types for CMMN abstractions like `Stage` and `Milestone` etc in this pull request: 

1. they are CMMN abstractions which improve readability of tests, but do not (yet?) exist in the Camunda API: currently it is very, very abstract to have to deal with a `CaseExecution` for basically everything

1. testing is complicated by the situation that certain objects "disappear" from the runtime database and their final state is eventually just verifiable by looking into the history tables (this is true in the BPMN, arena, too)

1. the `CaseExecution`type makes it very hard to enter into more specialised Assertions like e.g. a `HumanTaskAssert`, `StageAssert` or `MilestoneAssert`.

As I want to stick with the current approach **not to expose** any new types to the user of Camunda BPM Assert, I am currently thinking in the following direction to deal with the mentioned problems **instead of using holder types**, but in line with what we already did and have for BPMN:

1. A set of static helper methods - let's call it either `caseExecution()` or `planItem()` - makes it very easy to retrieve `CaseExecution`objects - so strictly works on the **runtime database**. For BPMN types we basically allowed to retrieve objects by definition key or with a custom query, either within the scope of a provided CaseInstance or within the scope of the CaseInstance asserted last. We can stick with that approach. I would currently not add more static helper methods like `humanTask()`, `stage()`etc because all of them could just return `CaseExecution` objects. In case camunda adds more specialised types, we could then introduce such functions later. I consider it to be good enough for now that we rely as a best practice on "speaking" definion keys, by e.g. writing:

    ```java
    CaseExecution reviewClaim = caseExecution("review_claim");
    ```

1. A set of generic assertions are available for `CaseExecution`s, which makes it e.g. possible to directly write

    ```java
    assertThat(caseExecution("review_claim")).isActive();
    ```

1. Furthermore, we should be able to check, that we got what we assumed to have: a human task., so we could e.g. write:

    ```java
    assertThat(caseExecution("review_claim")).isHumanTask();
    ```

1. Such `isHumanTask()`, `isStage()` assertions would also allow us to move into more specialised assertions like e.g. a `HumanTaskAssert` without introducing wrapper types. One could e.g. write:

    ```java
    assertThat(caseExecution("review_claim")).isHumanTask().hasCandidateGroup("clerks");
    ```

1. Furthermore - in line with what we have for BPMN and what you already started to implement, one could of course access assertions for objects existing within the scope of other ones. Here we could directly descend into the specialised assertions, by e.g. writing:

    ```java
    assertThat(stage).humanTask("review_claim").hasCandidateGroup("clerks");
    ```

1. When it comes to the history tables, I would vote to be a bit more cautious than what the current pull request proposes. Basically our current implementation is free to look into history tables in case it makes sense for the assertion and the `actual` object under test already disappeared from the runtime. So I would allow to look up a child `humanTask("review_claim")` from the history tables in case the parent caseExecution (in the example of type stage) is not in the runtime database anymore:

    ```java
    assertThat(stage).humanTask("review_claim").hasCandidateGroup("clerks");
    ```

    We already do such things, e.g. for historic process variables of finished process instances. But we do not look into history tables for disappeared process variables of running process instances or completed tasks of running process instances. I would therefore rather **not allow** to automatically retrieve that child `humanTask("review_claim")` from the history tables as long as the parent is still present in the runtime! In such a case I would urge the user to hold a reference. So, for a "living" stage with a completed task it should be possible to either write

    ```java
    assertThat(stage).humanTask("review_claim").isNull();
    ```

    or e.g. write

    ```java
    CaseExecution reviewClaim = caseExecution("review_claim"); // runtime data
    // ... something happens that leads to completion of task
    assertThat(reviewClaim).isCompleted(); // assertion checks history tables
    ```  

    In both cases, the rule would hold that we look at a "runtime typed" object under test, which may have ceased to be a runtime object since we got hold of it - in which case it is legitimate and not too much magic to look at its last known state in the history tables. But it would not be possible to write

    ```java
    assertThat(stage).humanTask("review_claim").isCompleted();
    ```

    as long as the stage itself lives as runtime object, because we would in my mind too easily mix up what we actually want to see here when asking for `humanTask("review_claim")`: a new runtime instance of that same task? Fair enough, if it exists. Or an old instance of that task? Better consistently not, I argue here.

**Happily awaiting any further comments!** In the meantime I will probably continue to experiment with the pull request and start to implement certain things in the proposed way. In case you don't have very good arguments against, I am currently inclined to merge everything of that pull request except of the last heavy refactoring which added the holder types.

**Comment by martinschimak** [comment]
As discussed above, I merged now most of your contribution into the cmmn_assertions branch here! 

**Many thanks again!** :100: 

I also pushed my refactoring to the cmmn_assertions branch - so that you can better evaluate the direction in which I would prefer to push the further CMMN assertions development. All your tests continue to work - with the exception of a few very little changes I had to make because of what I suggested above: I think it's probably safer to hold a reference to a "runtime database" object for a while longer than it lives in the database and then check its current status (against the history) than to automatically retrieve a fresh object by activity id (so maybe accidentally an unintented one!)  from the history tables. 

(I know that the consequences are a bit unsatisfying from a pure test fluency/readability pov, but at least it's also in line with what we do for BPMN assertions already. In case we improve upon that area in the future, I would also like to do it for all assertions, consistently, not just for the CMMN area.)

**Comment by malteser** [comment]
Hello Martin,

sorry for my late answer. I hadn't had enough time to read through all your comment and code and reply until now :)

I also talked to Simon last week and I am now more informed about the decisions made early in project. Especially the one to not build a friendlier API on top of camunda's. 
I fully understand the motivation behind these decisions and would like to see them to be more prominent, so others don't miss them easily. I will file a new issue for that.

How will we continue from here? You seem to be quite occupied with the merge/refactoring of my pull request. Beginning with the end of next week I should have some time I'd like to invest into this project. 
My idea is to take over the refactoring and add more CMMN test features starting next week. What do you think?

Malte

**Comment by martinschimak** [comment]
Hi @malteser!

Great to hear that you will have some time to invest into this project! I am actually quite happy about the refactoring status right now, the code is really simple and straightforward. What really needs to be done now step by step is the systematic work: implement, systematically test, javadoc and markdown every single feature.

I have added a file CMMN.md in which I list every public method I see at the moment for a first CMMN aware release 2.0. It also includes the methods you had listed in the test matrix document. 

I propose that whenever somebody has time to work on the project, to open an issue here, assign it to him/herself and make fully clear the (set of) methods working at. 

Many of the methods mentioned in the file are already implemented, but not systematically unit tested nor documented. What I mean with systematical tests is a dedicated test class for every public feature method similar to what we have done for BPMN. Such a test class would of course reach out to test every thinkable "input" into the method (parameters and database status) and the expected output. The tests we currently have are in my mind somewhere in between such systematical unit tests and more example oriented tests. What I mean with "example oriented" is that we e.g. test whether a stage completes when tasks are completed, that sentries behave as expected etc. This is something one needs for a concrete project, but I actually think we don't need that kind of tests for systematically unit testing assertions: it's enough that we ensure that we e.g. really see an expected "completed" caseExecution, no matter whether it completed because of a certain CMMN behaviour or not, it's enough that we ensure that we e.g. really see an expected exception if it is not the expected "completed" caseExecution, that the assertions behaves as expected when working on a "null" actual etc.

Having said that, it is very important that we have such example oriented tests, too. I see it as a shortcoming that we do not have a lot of such tests in the BPMN area so far. Such example oriented tests should in my mind really show the "best practices" of using the assertions and especially how clean test code should/could look like when using them. I therefore created a new module for cmmn examples, too. 

I guess, probably it makes sense to move some of the more example oriented tests we currently have overthere and refactor some other tests into more systematical unit tests!

I'd be thrilled to team up to complete that! I think: let's just get this done now! :smile:

**Comment by martinschimak** [comment]
We close this as discussed via mail - further contributions to the cmmn assertions branch are planned to be done with separate pull requests.

**Pull request closed without merging**
